In [3]:
pip install opencv-python


     --------------------------------------- 38.8/38.8 MB 28.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import matplotlib
import cv2 as cv

In [3]:
image = cv.imread("C:\\Users\\Savita Seharawat\\Desktop\\fulhaus\\Pizza.jpg")
# image.shape
# Using namedWindow() 
# A window with 'Display' name is created 
# with WINDOW_AUTOSIZE, window size is set automatically 
cv.namedWindow("Pizza", cv.WINDOW_AUTOSIZE) 
  
# using cv2.imshow() to display the image 
cv.imshow('Pizza', image) 
  
# Waiting 0ms for user to press any key 
cv.waitKey(0) 
  
# Using cv2.destroyAllWindows() to destroy 
# all created windows open on screen 
cv.destroyAllWindows() 


(1707, 2560, 3)

In [7]:
image = cv.imread("C:\\Users\\Savita Seharawat\\Desktop\\fulhaus\\Pizza.jpg")
image_2 = cv.resize(image,(800,400))
# Using namedWindow() 
# A window with 'Display' name is created 
# with WINDOW_AUTOSIZE, window size is set automatically 
cv.namedWindow("Pizza", cv.WINDOW_AUTOSIZE) 
  
# using cv2.imshow() to display the image 
cv.imshow('Pizza', image_2) 
  
# Waiting 0ms for user to press any key 
cv.waitKey(0) 
  
# Using cv2.destroyAllWindows() to destroy 
# all created windows open on screen 
cv.destroyAllWindows() 

In [3]:
import os

In [9]:
path = "C:\\Users\\Savita Seharawat\\Desktop\\cvi620\\week 2\\Bed"

In [12]:
img_names = os.listdir(path)
img_names[0:5]

['120cm Bed with underbed drawer.jpg',
 '140 cm double bed.jpg',
 '160 cm kingsize bed.jpg',
 '180 cm super kingsize bed.jpg',
 '90cm Bed with underbed drawer.jpg']

In [13]:
for image in img_names:
    print(image)

120cm Bed with underbed drawer.jpg
140 cm double bed.jpg
160 cm kingsize bed.jpg
180 cm super kingsize bed.jpg
90cm Bed with underbed drawer.jpg
Addison King Bed.jpg
Aidan Bed-Heavy Pebble Pewter-Queen.jpg
Aidan Bed-Vintage Tobacco-King.jpg
Aidan King Bed-Pebble Pewter.jpg
Aiden Velvet Bed.jpg
ALBI BED.jpg
Alexander Queen Bed.jpg
Alina Full Platform Bed Frame.jpg
Alina Queen Platform Bed Frame.jpg
Alina Twin Platform Bed Frame.jpg
Amaris Full Fabric Platform Bed with Round Splayed Legs.jpg
Amaris King Fabric Platform Bed with Squared Tapered Legs.jpg
Amaris Queen Fabric Platform Bed with Round Splayed Legs.jpg
Amaris Queen Fabric Platform Bed with Squared Tapered Legs in Gray _ Modway.jpg
Amaris Queen Fabric Platform Bed with Squared Tapered Legs.jpg
Amaris Twin Fabric Platform Bed with Round Splayed Legs.jpg
Amaris Twin Fabric Platform Bed with Squared Tapered Legs.jpg
Amelia Full Upholstered Fabric Bed.jpg
Amelia King Performance Velvet Bed.jpg
Amelia King Upholstered Fabric Bed.jpg


In [14]:
for image in img_names:
    image_full_path = path + "\\" + image
    img = cv.imread(image_full_path)
    img = cv.resize(img,(800,400))
    cv.imshow('Image', img) 
    cv.waitKey(0) 
cv.destroyAllWindows() 
    
    

In [17]:
for image in img_names:
    image_full_path = path + "\\" + image
    img = cv.imread(image_full_path)
    img = cv.resize(img,(800,400))
    cv.imshow('Image', img) 
    cv.waitKey(10) 
cv.destroyAllWindows() 

In [23]:
for image in img_names:
    image_full_path = path + "\\" + image
    img = cv.imread(image_full_path)
    img = cv.resize(img,(400,400))
    img_2 = np.hstack((img,img))
    img_4 = np.vstack((img_2,img_2))
    cv.imshow('Image', img_4) 
    cv.waitKey(1000) 
cv.destroyAllWindows() 

In [25]:
for image in img_names:
    image_full_path = path + "\\" + image
    img = cv.imread(image_full_path)
    img = cv.resize(img,(300,200))
    img_2 = np.hstack((img,img,img))
    img_4 = np.vstack((img_2,img_2))
    cv.imshow('Image', img_4) 
    cv.waitKey(100) 
cv.destroyAllWindows() 

In [32]:
# Start a video capture, using device's camera
webcam= cv.VideoCapture(0)

stop = False
while stop == False:
    ret,frame = webcam.read()
    
    if ret == True:
        cv.imshow('Pizza',frame)
        key = cv.waitKey(1) 
        if key == ord("q"):
            stop = True
webcam.release()
cv.destroyAllWindows()

In [6]:
video_path = r"C:\Users\Savita Seharawat\Desktop\COMP301\COMP301 - M2020 - Lesson 1  - Part 1 - Course Intro and Setup.mp4"
video_path2 = r"C:\Users\Savita Seharawat\Desktop\COMP301\COMP301 - M2020 - Lesson 1 - Part 2 - Intro to Linux.mp4"

In [27]:
# Start a video capture, using device's camera
webcam= cv.VideoCapture(video_path)

stop = False
while stop == False:
    ret,frame = webcam.read()
    
    if ret == True:
        image = cv.resize(frame,(400,200))
        cv.imshow('Pizza',image)
        key = cv.waitKey(1) 
        if key == ord("q"):
            stop = True
webcam.release()
cv.destroyAllWindows()

In [31]:
# Start a video capture, using device's camera
webcam= cv.VideoCapture(video_path)

stop = False
while stop == False:
    ret,frame = webcam.read()
    
    if ret == True:
        image = cv.resize(frame,(200,200))
        image_2 = np.hstack((image,image))
        image_4 = np.vstack((image_2,image_2))
        cv.imshow('image',image_4)
        key = cv.waitKey(1) 
        if key == ord("q"):
            stop = True
webcam.release()
cv.destroyAllWindows()

In [36]:
# Start a video capture, using device's camera
video_1= cv.VideoCapture(video_path)
video_2 = cv.VideoCapture(video_path2)
video_3 = cv.VideoCapture(0)


stop = False
while stop == False:
    ret_1,frame_1 = video_1.read()
    ret_2,frame_2 = video_2.read()
    ret_3,frame_3 = video_3.read()
    
    
    
    if ret_1 == True & ret_2 == True & ret_3 == True  :
        image_1 = cv.resize(frame_1,(200,200))
        image_2 = cv.resize(frame_2,(200,200))
        image_3 = cv.resize(frame_3,(200,200))
        
        
        image_4 = np.hstack((image_1,image_2))
        image_5 = np.hstack((image_3,image_3))
        
        image_6 = np.vstack((image_4,image_5))
        cv.imshow('image',image_6)
        key = cv.waitKey(1) 
        if key == ord("q"):
            stop = True
video_1.release()
video_2.release()
video_3.release()
cv.destroyAllWindows()

## Syntax of OpenCV cv2.imread() Method
## Syntax: cv2.imread(filename, flag) 

## Parameters:

## filename: The path to the image file.
## flag: The flag specifies the way how the image should be read.
## cv2.IMREAD_COLOR – It specifies to load a color image. Any transparency of image will be neglected. It is the default flag. Alternatively, we can pass integer value 1 for this flag.
## cv2.IMREAD_GRAYSCALE – It specifies to load an image in grayscale mode. Alternatively, we can pass integer value 0 for this flag. 
## cv2.IMREAD_UNCHANGED – It specifies to load an image as such including alpha channel. Alternatively, we can pass integer value -1 for this flag.

### Return Value: The cv2.imread() function return a NumPy array if the image is loaded successfully.

### Python OpenCV Read Image – cv2 imread()

In [47]:
# Load the image
image = cv.imread(r"C:\Users\Savita Seharawat\Desktop\cvi620\week 2\gfg.jpeg")

# Display the image
cv.imshow("Image", image)
print(image)
print(image.shape)

# Wait for the user to press a key
cv.waitKey(0)

# Close all windows
cv.destroyAllWindows()

[[[214 223 232]
  [214 223 232]
  [214 223 232]
  ...
  [230 241 249]
  [230 241 249]
  [230 241 249]]

 [[214 223 232]
  [214 223 232]
  [214 223 232]
  ...
  [230 241 249]
  [230 241 249]
  [230 241 249]]

 [[214 223 232]
  [214 223 232]
  [214 223 232]
  ...
  [230 241 249]
  [230 241 249]
  [230 241 249]]

 ...

 [[218 233 242]
  [200 215 224]
  [192 207 216]
  ...
  [141 146 155]
  [141 146 155]
  [141 146 155]]

 [[195 210 219]
  [188 203 212]
  [191 206 215]
  ...
  [142 147 156]
  [142 147 156]
  [142 147 156]]

 [[170 185 194]
  [191 206 215]
  [206 221 230]
  ...
  [142 147 156]
  [142 147 156]
  [142 147 156]]]
(168, 300, 3)


## Python OpenCV Read image grayscale
## In this example, we are reading the image as a greyscale image. Both color and grayscale images are acceptable as input.

In [48]:
# Load the image
image = cv.imread(r"C:\Users\Savita Seharawat\Desktop\cvi620\week 2\gfg.jpeg",cv2.IMREAD_GRAYSCALE)

# Display the image
cv.imshow("Image", image)
print(image)
print(image.shape)

# Wait for the user to press a key
cv.waitKey(0)

# Close all windows
cv.destroyAllWindows()

[[225 225 225 ... 242 242 242]
 [225 225 225 ... 242 242 242]
 [225 225 225 ... 242 242 242]
 ...
 [234 216 208 ... 148 148 148]
 [211 204 207 ... 149 149 149]
 [186 207 222 ... 149 149 149]]
(168, 300)


## Python OpenCV | Read PNG Image with Transparency
## In this example, we are reading the image with the transparency channel.

In [49]:
# Load the image
image = cv.imread(r"C:\Users\Savita Seharawat\Desktop\cvi620\week 2\gfg.jpeg",cv2.IMREAD_UNCHANGED)

# Display the image
cv.imshow("Image", image)

# Wait for the user to press a key
cv.waitKey(0)

# Close all windows
cv.destroyAllWindows()

## imread() and Color Channels
### A NumPy array is produced after reading an image file with the cv2.imread() method. 
### By default, the image is saved in the BGR color space. 
### As a result, the blue, green, and red color channels, respectively, correspond to the first three channels of the NumPy array.

In [43]:
r1 = image[:,:,0] # get blue channel
g1 = image[:,:,1] # get green channel
b1 = image[:,:,2] # get red channel

In [44]:
r1

array([[214, 214, 214, ..., 230, 230, 230],
       [214, 214, 214, ..., 230, 230, 230],
       [214, 214, 214, ..., 230, 230, 230],
       ...,
       [218, 200, 192, ..., 141, 141, 141],
       [195, 188, 191, ..., 142, 142, 142],
       [170, 191, 206, ..., 142, 142, 142]], dtype=uint8)

### OpenCV library has powerful function named as cv2.imshow(). Which shows the NumPy array in the form of an Image.
### 
### cv2.imshow() function takes any size of NumPy array and shows the image in the same size in the window. If the image resolution is more than a system screen resolution then it shows only those pixel which fits in the screen.

### Ex: Image resolution is (2000,1000) (widht, height) and screen resolution is (1000,500). Then cv2.imshow() function shows only (1000,500) pixels of image not all. To solve this problem you can resize your image then show using cv2.imsho() function.
### 
### Syntax: cv2.imshow( windows_name, numpy_array)
### windows_name: string value
### numpy_array: 2d or 3d NumPy array

In [54]:
import cv2
import numpy as np
 
matrix = np.zeros((200,200)) # numpy array with width =200, height=200
print(matrix)
print(matrix.shape)
 
cv2.imshow("Zeros matrix", matrix) # show numpy array
 
cv2.waitKey(0) # wait for ay key to exit window
cv2.destroyAllWindows() # close all windows

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(200, 200)


In [55]:
# Load the image
image = cv.imread(r"C:\Users\Savita Seharawat\Desktop\cvi620\week 2\gfg.jpeg",cv2.IMREAD_UNCHANGED)

# Display the image
cv.imshow("Image", image)

# Wait for the user to press a key
cv.waitKey(0)

# Close all windows
cv.destroyAllWindows()

### Show same image in multiple windows

In [57]:
# Load the image
image = cv.imread(r"C:\Users\Savita Seharawat\Desktop\cvi620\week 2\gfg.jpeg",cv2.IMREAD_UNCHANGED)

# Display the image
cv.imshow("Image1", image)
cv.imshow("Image2", image)

# Wait for the user to press a key
cv.waitKey(0)

# Close all windows
cv.destroyAllWindows()

## How to save image or NumPy array as image
## Save Numpy Array

In [9]:
#For detail Explanation watch prime video: video link >>> https://youtu.be/6VqbeozUgWQ
 
import cv2 as cv
import numpy as np
import os
 
rand_array = np.random.randint(255, size = (300,600,3))
 
cv2.imwrite("rand_np_array.png", rand_array) # imwrite(filename, img[, params])
 
img = cv2.imread("rand_np_array.png")
cv2.imshow('image', img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

## Save Image

In [59]:

img_path = r'C:\\Users\\Savita Seharawat\\Desktop\\fulhaus\\Pizza.jpg'
 
img = cv2.imread(img_path)
cv2.imshow('image', img)
 
cv2.imwrite("model_write.png", img)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
#os.mkdir("video_to_image_1") # create directory
# Start a video capture, using device's camera
webcam= cv.VideoCapture(video_path)
 
img_count = 1
stop = False
while stop == False:
    ret,frame = webcam.read()
    
    is_img_write = cv.imwrite(f"video_to_image_1\image{img_count}.jpeg", frame)
    
    if ret == True:
        image = cv.resize(frame,(400,200))
        cv.imshow('Pizza',image)
        key = cv.waitKey(1) 
        img_count += 1
        if key == ord("q"):
            stop = True
webcam.release()
cv.destroyAllWindows()